作業1：求陣列([1,2,3,4,5,6,7]平均值(期望值)

In [1]:
from numpy import array
from numpy import mean
v = array([1,2,3,4,5,6,7])
print(v)
result = mean(v)
print(result)

[1 2 3 4 5 6 7]
4.0


作業2：求以下二維矩陣行與列的平均值

In [3]:
from numpy import array
from numpy import mean
M = array([[1,2,3,4,5,6],[6,5,4,3,2,1]])
print(M)
col_mean = mean(M, axis=0)
print("行平均：")
print(col_mean)
row_mean = mean(M, axis=1)
print("列平均：")
print(row_mean)

[[1 2 3 4 5 6]
 [6 5 4 3 2 1]]
行平均：
[3.5 3.5 3.5 3.5 3.5 3.5]
列平均：
[3.5 3.5]


作業3：求以下向量變異數(方差)

In [7]:
from numpy import array
from numpy import var
v = array([1,3,5,7,9,11])
print(v)
result = var(v, ddof=1)
print("變異數")
print(result)

[ 1  3  5  7  9 11]
變異數
14.0


作業4：計算以下陣列行標準差與列標準差

In [8]:
from numpy import array
from numpy import std
M = array([[1,2,3,4,5,6],[6,5,4,3,2,1]])
print(M)
col_mean = std(M, ddof=1, axis=0)
print(col_mean)
row_mean = std(M, ddof=1, axis=1)
print(row_mean)

[[1 2 3 4 5 6]
 [6 5 4 3 2 1]]
[3.53553391 2.12132034 0.70710678 0.70710678 2.12132034 3.53553391]
[1.87082869 1.87082869]


作業5：求以下陣列協方差

In [9]:
from numpy import array
from numpy import cov
x = array([1,2,3,4,5,6,7,8,9])
print(x)
y = array([4,3,2,1,9,8,7,6,5])
print(y)
Sigma = cov(x, y)[0, 1]
print("兩向量協方差")
print(Sigma)

[1 2 3 4 5 6 7 8 9]
[4 3 2 1 9 8 7 6 5]
兩向量協方差
3.75


作業6：求下列兩向量相關係數

In [10]:
from numpy import array
from numpy import corrcoef
x = array([1,2,3,4,5,6,7,8,9])
print(x)
y = array([4,3,2,1,9,8,7,6,5])
print(y)
Sigma = corrcoef(x, y)
print(Sigma)

[1 2 3 4 5 6 7 8 9]
[4 3 2 1 9 8 7 6 5]
[[1.  0.5]
 [0.5 1. ]]
